### ISSUE TITLE
Python simulation

### ISSUE THREAD

**Issue by xinxueHEAI** [VintageGold/Data690_MathML#6]
Can you guys figure out a way to numerically compute "pi"?

hint: do some research in numpy.random.uniform, and think about how "pi" appear in a 2-dimension plane. 

Try not to use other sources, but if you do, please cite. 

Also, feel free to bring in others.

**Comment by xinxueHEAI** [comment]
np.random.uniform is just a way to generate points. 

Eventually, you need something to relate it to an area of a circle. 
Think about how to construct a circle in a 2-dimensional (x,y) plane, mathematically.

**Comment by VintageGold** [comment]
I drew a circle by using np.linspace and then feeding that matrix into np.cos and np.sin. Still doing more research on how to use np.random.uniform and np.pi to draw a circle.

```import numpy as np
import matplotlib.pyplot as plt

t = np.linspace((100,0),(0,100),100)
print(t.shape)
p,ax = plt.plot(np.cos(t),np.sin(t))
```

**Comment by xinxueHEAI** [comment]
Good thinking. I think you are getting there, although think about how to use x and y as axes instead of sin and cos (polar coordinates). 
How do you use x and y to represent a (unit) circle and the area inside?

**Comment by wbfrench1** [comment]
def dist(x1: float, y1: float, x2: float, y2: float) :
  return np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

def point_on_circumference (x:float):
  return np.sqrt(9 - x**2)

def arc_length( start_x: float, radius: float):
    x_coords = list(np.linspace(0,radius,50))
    y_coords =[]
    approx_arc_length = 0
    for x in x_coords:
      y_coords.append(point_on_circumference(x))
    i = 1
    while i < (len(x_coords) -1):
      approx_arc_length += dist(x_coords[i],y_coords[i],x_coords[i+1],y_coords[i+1])
      i += 1
    return approx_arc_length, x_coords, y_coords

result, x, y = arc_length(0,3)

pi = (result*4)/6

**Comment by Colsai** [comment]
Hey Barker and Adam, 
Apologies on not really contributing much earlier, and really appreciate the working answer. I completely did not make that connection between uniform dist and populating points with the area of a unit circle until the demonstration in class. 

Wanted to at least provide some working code for the class alternate solution, and will think about the primary solution using linspace. 

#Populating Points and Comparing areas
def estimate_pi(num_pts = 10000):  
    outside_pts, inside_pts = 0,0  
    for point in range(0,num_pts):  
            x, y = np.random.uniform(low=-1.0, high=1.0, size=None), np.random.uniform(low=-1.0, high=1.0, size=None)
            if x ** 2 + y ** 2 >= 1:  
                outside_pts+=1  
            else:  
                inside_pts+=1  
    return print(f"Estimate for PI: {inside_pts/(inside_pts+outside_pts)*4}")

estimate_pi()

**Comment by wbfrench1** [comment]
Hey Scott!

No worries at all!  Thank you for putting this together!  I apologize for
not coordinating a group meeting…it was just really busy last week and I
was exhausted!

Cheers!
Barker
